[general]
live_config_reload = true
import = ["./themes/themes/one_dark.toml"]

[font]
size = 10

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
opacity = 0.9

[window.padding]
x = 6
y = 2
